### ISSUE TITLE
Hugo support to display the Readme markdown

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-content-integrity#12]

**Comment by GINAGC** [comment]
@chrisdiao this should be assigned to a devops person, what is the goal on this task?

**Comment by GINAGC** [comment]
why this one is P1? it doesn't sounds like. @chrisdiao

**Comment by rajmbcoderx** [comment]
Setting up hugo for the current state doesn't add any value, we can close this ticket for now. Its just readme content tht needs to be handled and it would be an overhead to configure HUGO for it.
