### ISSUE TITLE
Create docker compose and docker infrastructure for extraction engine, Tika

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-content-integrity#2]

**Comment by MaNe2020** [comment]
I can see Tika, Elastic and Swagger as part of `docker-compose`.
![image](https://user-images.githubusercontent.com/70108899/122485659-bfef9580-cfd7-11eb-9a91-f1c92d13e93d.png)

@gmuditdce is Hugo included in this?
If not ticket title needs to be changes and if Hugo is to be added, new issue should be created. @chrisdiao FYI

**Comment by MaNe2020** [comment]
@gmuditdce and @chrisdiao pls confirm if Hugo is part of this or not.

**Comment by gmuditdce** [comment]
@MaNe2020 title changed, Hugo is not yet included, there is another task open for Hugo.

**Comment by MaNe2020** [comment]
@chrisdiao docker compose for Tika and extraction engine is in place. Moving this one for Release.

**Comment by chrisdiao** [comment]
This is included in v0.1.0 release
