### ISSUE TITLE
Deployment of gw-visualizer tools in ec2 (fastapi, visualizer, ELK)

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#24]

**Comment by gmuditdce** [comment]
Minor change changes and deployment done at
http://52.211.175.199/gw-vlc-tool/docs
http://52.211.175.199:8000/gw-vlc-visualiser
http://52.211.175.199:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0)[…](language:kuery,query:''),sort:!(!(timestamp,desc)))
http://52.211.175.199:5601/app/dashboards#/view/2c0f89b0-c6b8-11eb-9336-db88a5dfb4c4?_g=(filt[…]imeRestore:!f,title:ComparisonReults,viewMode:view)
http://52.211.175.199:5601/app/dashboards#/view/f378d3c0-c6be-11eb-9336-db88a5dfb4c4?_g=(filt[…]meRestore:!f,title:ComparisionStatus,viewMode:view)

**Comment by MaNe2020** [comment]
@gmuditdce can you share via passbolt password for accessing Elastic.
And also how we can deploy this without using above URLs?

**Comment by gmuditdce** [comment]
hi @MaNe2020 Deployment of visualizer instructions are at https://github.com/filetrust/gw-visual-layer-comparison-tool/tree/review-branch
ELK docker image can be deployed using instructions at https://github.com/deviantony/docker-elk
I will send you above deployment elk credentials on slack? I don't have passbolt yet.

**Comment by MaNe2020** [comment]
Above links are accessible and usable. Verifying the work done and moving it to release.

**Comment by chrisdiao** [comment]
This is included in v0.1.0 release
