### ISSUE TITLE
Add a test runs from the text compare as visualizations in Elastic

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#27]
- [x]  content integrity deployment will provide a fastapi to compare texts and metadata for any two files
- [x] any files compared with these two endpoints will return comparison results in the form of json
- [x] all comparison stats will be made available in elastic and kibana for visualizations

**Comment by chrisdiao** [comment]
@MaNe2020 , could you please provide update on this, please?

**Comment by MaNe2020** [comment]
This one is ready for release.
Created new: https://github.com/filetrust/cdr-content-integrity/issues/66 for additional work.

**Comment by chrisdiao** [comment]
Included in release v0.2.0
