### ISSUE TITLE
Once we have the list of files (#395-#397) use tools like pdfinfo to extract metadata and JavaScript

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#35]
@kekesimarti commented on [Thu May 20 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/398)

* Pdfinfo:  [ https://hub.docker.com/r/gkmr/pdf-tools](https://hub.docker.com/r/gkmr/pdf-tools)
* Described here:  [https://stackoverflow.com/questions/29342542/how-can-i-extract-a-javascript-from-a-pdf-file-with-a-command-line-tool ](https://stackoverflow.com/questions/29342542/how-can-i-extract-a-javascript-from-a-pdf-file-with-a-command-line-tool)
* Another great tool to use is:  [ https://tika.apache.org/](https://tika.apache.org/)

Reach out to  @Elvin White @Greg Mann (GW) to see what tools they have to extract data from files

---

@MaNe2020 commented on [Mon Jun 07 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/398#issuecomment-855893792)

Tool suggestion from Elvin: https://www.miraplacid.com/mtd/sdk.shtml

I will run high threat files from govUk through:
- https://www.miraplacid.com/mtd/sdk.shtml
- https://hub.docker.com/r/gkmr/pdf-tools
- https://tika.apache.org/
- CDR Plugin

and compare results
will create doc after this is done.

**Comment by MaNe2020** [comment]
As this is done in more depth in content-integrity I will go ahead and close this issue. @chrisdiao FYI
