### ISSUE TITLE
Investigate tools for MS Office file comparison. Document the results

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-content-integrity#40]

**Comment by ggrig** [comment]
The output of the task is documented at 
https://github.com/filetrust/cdr-content-integrity/blob/develop/docs/ms-office-comparison-tools.md

**Comment by chrisdiao** [comment]
@MaNe2020 , could you please check and verify again, please.

**Comment by MaNe2020** [comment]
@chrisdiao this is documented. 4 tools have been linked in README. I suppose next would be to check how they work and which is the best one to use, but first part of finding and documenting them is done.
Moving it for the release.

**Comment by chrisdiao** [comment]
This is included in v0.1.0 release
