### ISSUE TITLE
To deploy and use a pdf-converter tool that takes files and converts them to pdf

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#44]

**Comment by MaNe2020** [comment]
@chrisdiao @gmuditdce this issue does not have any details.
Pls provide them in order to test this.

Above PR has 66 files changed and 21 commit!

**Comment by gmuditdce** [comment]
Hi @MaNe2020 
1. Execute docker-compose up from the main directory
2. There are 2 places to check pdf conversion
 - There is a fastpi endpoint that takes a file and responds back with a pdf-converted file (on port 8080)
 
 
![image](https://user-images.githubusercontent.com/71660612/123742904-0f806c00-d8ca-11eb-8758-b56cfb1805a2.png)

 
 - There is a UI tool on port 4443 to use the functionality on pdf and image conversion of any file

![image](https://user-images.githubusercontent.com/71660612/123742941-1f984b80-d8ca-11eb-87f5-921d374be8aa.png)

**Comment by chrisdiao** [comment]
@MaNe2020 , could you please provide update on this, please?

**Comment by MaNe2020** [comment]
@gmuditdce cannot seem to connect to any of those on WIN
![image](https://user-images.githubusercontent.com/70108899/124042876-1b734780-da0a-11eb-9083-d0e3158985de.png)

Do you maybe have idea what is this about?

**Comment by gmuditdce** [comment]
Yes @MaNe2020 .env files are missing i looks like from the setup.
The README on this

Developers need to add the following environment files and variables before creating the docker-compose stack to use pdf features

Create file /cdr-pdf-conversion/backend/express/.env with proper values for

PORT                    = 4443
REACT_CLIENT_HOST       = pdf-client
REACT_CLIENT_PORT       = 5443
Values will normally remain the same as above

Create file ./cdr-pdf-conversion/frontend/server/.env with proper values for

PORT                    = 5443
REACT_APP_API_HOST      = localhost
REACT_APP_API_PORT      = 4443
REACT_APP_CLIENT_PORT   = 5443
Only the value of REACT_APP_API_HOST may need to be changed - it depends on the deployment host

**Comment by MaNe2020** [comment]
@chrisdiao I have verified this on linux.
@gmuditdce it was not working on Linux also but what I needed to change was 
`REACT_CLIENT_HOST = pdf-client` to `REACT_CLIENT_HOST = localhost`
Moving to release column.

**Comment by chrisdiao** [comment]
Included in v0.2.0 release
