### ISSUE TITLE
To analyze the XML reports of the 250 vs the 50 mismatches

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#58]
To see if there are any similarities that make one group stand out

**Comment by reubenkavalov** [comment]
Content groups exclusive to each fileset:

![image](https://user-images.githubusercontent.com/53289320/123980951-f0e4a880-d98f-11eb-8df7-554a0368a89c.png)
![image](https://user-images.githubusercontent.com/53289320/123980978-f641f300-d98f-11eb-9b61-4162d639e5d4.png)

File types **_(no .doc or .docx filetypes in 250-fileset)_**:

![image](https://user-images.githubusercontent.com/53289320/123981663-71a3a480-d990-11eb-91a5-59be0ea14374.png)
![image](https://user-images.githubusercontent.com/53289320/123981742-7a947600-d990-11eb-91fd-a24516023708.png)
