### ISSUE TITLE
Coveralls integration for the repo

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-content-integrity#8]

**Comment by GINAGC** [comment]
@chrisdiao can you add more details to this task?

**Comment by MaNe2020** [comment]
@chrisdiao @rajmbcoderx I need more info on this one. What is done and how I can verify that?

**Comment by rajmbcoderx** [comment]
@MaNe2020 This has nothing to do with the source code. Once the changes are merged, this should generate coverall report for all the PRs and for the branch.

A new workflow has been added to run all the unit tests when a PR is created and changes are merged to develop or master, also generating the coverall report.

**Comment by MaNe2020** [comment]
Oh @rajmbcoderx @chrisdiao this is cool
![image](https://user-images.githubusercontent.com/70108899/123146946-c3af6c00-d45e-11eb-8c41-e7d1da8f48bc.png)
![image](https://user-images.githubusercontent.com/70108899/123146992-d164f180-d45e-11eb-9da6-0adc7a7190b0.png)

This is ready for release and I created task to document this and maybe have it in the rest of the projects: https://github.com/k8-proxy/EAP-Docs/issues/12

**Comment by chrisdiao** [comment]
This is included in v0.1.0 release
