### ISSUE TITLE
Create test CI pipeline 

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-content-integrity#9]

**Comment by GINAGC** [comment]
@chrisdiao this should be assigned to a devops person, what is the goal on this task?

**Comment by MaNe2020** [comment]
@chrisdiao @rajmbcoderx I need more info on this one. What is done and how I can verify that?

**Comment by MaNe2020** [comment]
![image](https://user-images.githubusercontent.com/70108899/123248265-05382980-d4e8-11eb-9960-28014d1969d0.png)

**Comment by chrisdiao** [comment]
This is included in v0.1.0 release
